# Generated by Django 4.2.16 on 2024-10-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=225)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.blood')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login_details', to='bldmsapp.logindata')),
            ],
            options={
                'ordering': ['first_name', 'middle_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('units', models.FloatField()),
                ('required_on', models.DateTimeField()),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.blood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BloodCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('units', models.FloatField()),
                ('transferred_on', models.DateTimeField(blank=True, null=True)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.blood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='bldmsapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_login_details', to='bldmsapp.logindata')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
