# Generated by Django 4.2.16 on 2024-10-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0005_logindata_groups_logindata_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindetails',
            old_name='login',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=225)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.blood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login_details', to='bldmsapp.logindata')),
            ],
            options={
                'ordering': ['first_name', 'middle_name', 'last_name'],
            },
        ),
        migrations.AlterField(
            model_name='bloodcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='bldmsapp.registereduser'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.registereduser'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
