# Generated by Django 4.2.16 on 2024-10-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0008_logindata_groups_logindata_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='logindata',
            name='user_permissions',
        ),
    ]
