# Generated by Django 4.2.16 on 2024-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0009_remove_logindata_groups_remove_logindata_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.AddField(
            model_name='admindetails',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admindetails',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admindetails',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
