# Generated by Django 4.2.16 on 2024-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0010_remove_admindetails_user_remove_registereduser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
