# Generated by Django 4.2.16 on 2024-10-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0011_alter_registereduser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcollection',
            name='units',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('dob', models.IntegerField(max_length=10)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.blood')),
            ],
        ),
        migrations.AlterField(
            model_name='bloodcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_details', to='bldmsapp.donor'),
        ),
    ]
