# Generated by Django 4.2.16 on 2024-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0012_alter_bloodcollection_units_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.IntegerField(),
        ),
    ]
