# Generated by Django 4.2.16 on 2024-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0013_alter_bloodrequest_units_alter_donor_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcollection',
            name='blood',
        ),
    ]
