# Generated by Django 4.2.16 on 2024-10-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0014_remove_bloodcollection_blood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='name',
            new_name='blood',
        ),
    ]
