# Generated by Django 4.2.16 on 2024-10-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0015_rename_name_blood_blood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='blood',
            new_name='name',
        ),
    ]
