# Generated by Django 4.2.16 on 2024-10-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0017_bloodcollection_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcollection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.admindetails'),
        ),
    ]
