# Generated by Django 4.2.16 on 2024-10-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0018_bloodcollection_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
