# Generated by Django 4.2.16 on 2024-10-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0019_bloodrequest_age_bloodrequest_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodcollection',
            old_name='created',
            new_name='collected_date',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='created',
            new_name='created_date',
        ),
    ]
