# Generated by Django 4.2.16 on 2024-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0022_alter_bloodrequest_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
