# Generated by Django 4.2.16 on 2024-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0023_alter_bloodrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
