# Generated by Django 4.2.16 on 2024-10-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0025_alter_bloodrequest_required_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_on',
            field=models.DateTimeField(),
        ),
    ]
