# Generated by Django 4.2.16 on 2024-10-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0027_alter_bloodrequest_required_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.registereduser'),
        ),
    ]
