# Generated by Django 4.2.16 on 2024-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0028_bloodrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hasRecived',
            field=models.BooleanField(default=False),
        ),
    ]
