# Generated by Django 4.2.16 on 2024-10-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0029_bloodrequest_hasrecived'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcollection',
            name='total_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodcollection',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
