# Generated by Django 4.2.16 on 2024-10-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0030_bloodcollection_total_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcollection',
            name='total_units',
        ),
        migrations.RemoveField(
            model_name='bloodcollection',
            name='transferred_on',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.bloodcollection'),
        ),
    ]
