# Generated by Django 4.2.16 on 2024-10-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0031_remove_bloodcollection_total_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donor_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.bloodcollection'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='received_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bldmsapp.admindetails'),
        ),
    ]
