# Generated by Django 4.2.16 on 2024-10-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0033_bloodcollection_total_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodcollection',
            old_name='units',
            new_name='transfer_units',
        ),
    ]
