# Generated by Django 4.2.16 on 2024-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0034_rename_units_bloodcollection_transfer_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcollection',
            name='transfer_units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
