# Generated by Django 4.2.16 on 2024-10-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldmsapp', '0035_alter_bloodcollection_transfer_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcollection',
            name='transfer_units',
        ),
    ]
